<a href="https://colab.research.google.com/github/Sru-j/daily_lab_activities/blob/main/bikes_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#data loading

In [3]:
import os
import glob
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive')

DIR = "/content/drive/My Drive/Colab Notebooks/data/"
os.chdir(DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
os.chdir(DIR)
!ls

 699.csv	      ioc_feed.xml	    superstore.dbf
'alerts (1).json'     netflow.jsonl	    superstore_json.json
 alerts.json	      PlayTennis.csv	    superstore_tsv.tsv
 auth_logs.csv	      PlayTennisTest.csv    superstore.txt
 Bikes.xlsx	      security_policy.yml   superstore_xls.xlsx
 car_dataset.csv      soc_alerts.xlsx	    Titanic_Dataset.csv
 dns_queries.tsv      soc_dump.sql	    unclean_data.csv
 incident_notes.txt   superstore.csv	    web_access.log

In [8]:
datafile='Bikes.xlsx'
filename = DIR+'/'+datafile
df = pd.read_excel(filename)
df

,ID,Marital Status,Gender,Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Purchased Bike
0,12496,M,F,40000,1,Bachelors,Skilled Manual,Yes,0,0-1 Miles,Europe,42,No
1,24107,M,M,30000,3,Partial College,Clerical,Yes,1,0-1 Miles,Europe,43,No
2,14177,M,M,80000,5,Partial College,Professional,No,2,2-5 Miles,Europe,60,No
3,24381,S,M,70000,0,Bachelors,Professional,Yes,1,5-10 Miles,Pacific,41,Yes
4,25597,S,M,30000,0,Bachelors,Clerical,No,0,0-1 Miles,Europe,36,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1021,16466,S,F,20000,0,Partial High School,Manual,No,2,0-1 Miles,Europe,32,Yes
1022,19273,M,F,20000,2,Partial College,Manual,Yes,0,0-1 Miles,Europe,63,No
1023,22400,M,M,10000,0,Partial College,Manual,No,1,0-1 Miles,Pacific,26,Yes
1024,20942,S,F,20000,0,High School,Manual,No,1,5-10 Miles,Europe,31,No
1025,18484,S,M,80000,2,High School,Skilled Manual,No,2,1-2 Miles,Pacific,50,Yes

#data inspect

In [9]:
df.columns

Index(['ID', 'Marital Status', 'Gender', 'Income', 'Children', 'Education',
       'Occupation', 'Home Owner', 'Cars', 'Commute Distance', 'Region', 'Age',
       'Purchased Bike'],
      dtype='object')

In [14]:
df.shape

(1026, 13)

In [16]:
df.size

13338

In [17]:
df.dtypes

id                   int64
marital_status      object
gender              object
income               int64
children             int64
education           object
occupation          object
home_owner          object
cars                 int64
commute_distance    object
region              object
age                  int64
purchased_bike      object
dtype: object

In [20]:
df.isnull().sum()

id                  0
marital_status      0
gender              0
income              0
children            0
education           0
occupation          0
home_owner          0
cars                0
commute_distance    0
region              0
age                 0
purchased_bike      0
dtype: int64

In [24]:
df.describe()

                 id         income     children         cars          age
count   1026.000000    1026.000000  1026.000000  1026.000000  1026.000000
mean   19969.196881   56208.576998     1.892788     1.437622    44.138402
std     5332.672942   31293.284007     1.626670     1.125538    11.349282
min    11000.000000   10000.000000     0.000000     0.000000    25.000000
25%    15304.750000   30000.000000     0.000000     1.000000    35.000000
50%    19744.000000   60000.000000     2.000000     1.000000    43.000000
75%    24457.750000   70000.000000     3.000000     2.000000    52.000000
max    29447.000000  170000.000000     5.000000     4.000000    89.000000

In [35]:
df['region'].value_counts()

region
North America    508
Europe           316
Pacific          202
Name: count, dtype: int64

In [37]:
df['education'].value_counts()

education
Bachelors              311
Partial College        278
High School            184
Graduate Degree        175
Partial High School     78
Name: count, dtype: int64

In [38]:
df['occupation'].value_counts()

occupation
Professional      280
Skilled Manual    259
Clerical          187
Management        174
Manual            126
Name: count, dtype: int64

In [39]:
#check if there is any other values apart from M and F
df['gender'].value_counts()

gender
M    525
F    501
Name: count, dtype: int64

In [41]:
#check if there is any other values apart from M and S
df['marital_status'].value_counts()

marital_status
M    549
S    477
Name: count, dtype: int64

#data cleaning

In [25]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')
df.columns

Index(['id', 'marital_status', 'gender', 'income', 'children', 'education',
       'occupation', 'home_owner', 'cars', 'commute_distance', 'region', 'age',
       'purchased_bike'],
      dtype='object')

In [27]:
import re

def clean_commute(x):
    x = x.lower().replace('miles', '').strip()

    if '-' in x:  # range like 1-2
        nums = [int(n) for n in x.split('-')]
        return sum(nums) / len(nums)  # average

    elif '+' in x:  # like 10+
        return int(x.replace('+', ''))

    else:  # single value like 1
        return int(re.findall(r'\d+', x)[0])

In [28]:
df['commute_distance'] = df['commute_distance'].apply(clean_commute)

In [29]:
df['commute_distance']

0       0.5
1       0.5
2       3.5
3       7.5
4       0.5
       ...
1021    0.5
1022    0.5
1023    0.5
1024    7.5
1025    1.5
Name: commute_distance, Length: 1026, dtype: float64

In [30]:
df['commute_distance'].describe()

count    1026.000000
mean        3.535575
std         3.426005
min         0.500000
25%         0.500000
50%         1.500000
75%         7.500000
max        10.000000
Name: commute_distance, dtype: float64

In [31]:
df['commute_distance']=df['commute_distance'].astype(int)
df['commute_distance'].dtypes

dtype('int64')

In [34]:
df.head()

,id,marital_status,gender,income,children,education,occupation,home_owner,cars,commute_distance,region,age,purchased_bike
0,12496,M,F,40000,1,Bachelors,Skilled Manual,Yes,0,0,Europe,42,No
1,24107,M,M,30000,3,Partial College,Clerical,Yes,1,0,Europe,43,No
2,14177,M,M,80000,5,Partial College,Professional,No,2,3,Europe,60,No
3,24381,S,M,70000,0,Bachelors,Professional,Yes,1,7,Pacific,41,Yes
4,25597,S,M,30000,0,Bachelors,Clerical,No,0,0,Europe,36,Yes